# Generated by Django 2.2.12 on 2020-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_logfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='PostedDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
