# Generated by Django 2.2.12 on 2020-04-28 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_auto_20200428_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='PostedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
